// Merges the dated content packs (js/content_packs.js, generated by tools/content_packs.py)
// into the existing banks at load time. Additive and idempotent; a pack whose "released" date
// is still in the future is skipped. Mirrors apply_content_packs() in kids_exercise_app.py.
(function applyContentPacks() {
  if (typeof CONTENT_PACKS === "undefined") return;
  const today = new Date().toISOString().slice(0, 10);
  const templateBanks = { add: ADD_TEMPLATES, sub: SUB_TEMPLATES, mul: MUL_TEMPLATES, div: DIV_TEMPLATES };

  for (const pack of CONTENT_PACKS) {
    if ((pack.released || "") > today) continue;

    for (const [age, passages] of Object.entries(pack.reading_passages || {})) {
      const bank = APP_DATA.READING_PASSAGES[age];
      const have = new Set(bank.map((p) => p.text));
      for (const p of passages) if (!have.has(p.text)) { bank.push(p); have.add(p.text); }
    }

    for (const [label, easy, hard] of [
      ["synonyms", APP_DATA.SYNONYMS, APP_DATA.SYNONYMS_HARD],
      ["antonyms", APP_DATA.ANTONYMS, APP_DATA.ANTONYMS_HARD],
    ]) {
      for (const [tier, bank] of [["easy", easy], ["hard", hard]]) {
        for (const [word, other] of Object.entries((pack[label] || {})[tier] || {})) {
          if (!(word in easy) && !(word in hard)) bank[word] = other;
        }
      }
    }

    for (const [tier, bank] of [["easy", APP_DATA.RHYME_SETS], ["hard", APP_DATA.RHYME_SETS_HARD]]) {
      const heads = new Set([...APP_DATA.RHYME_SETS, ...APP_DATA.RHYME_SETS_HARD].map((g) => g[0]));
      for (const group of (pack.rhymes || {})[tier] || []) {
        if (!heads.has(group[0])) { bank.push(group.slice()); heads.add(group[0]); }
      }
    }

    const haveAnalogies = new Set(APP_DATA.ANALOGY_PAIRS.map((t) => `${t[0]}|${t[2]}`));
    for (const t of pack.analogies || []) {
      const key = `${t[0]}|${t[2]}`;
      if (!haveAnalogies.has(key)) { APP_DATA.ANALOGY_PAIRS.push(t.slice()); haveAnalogies.add(key); }
    }

    for (const [op, templates] of Object.entries(pack.word_problem_templates || {})) {
      const bank = templateBanks[op];
      if (!bank) continue;
      for (const t of templates) if (!bank.includes(t)) bank.push(t);
    }
  }
})();
